#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Camera2VideoSample.Resource", IsApplication=true)]

namespace Camera2VideoSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Camera2VideoSample.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Camera2VideoSample.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Camera2VideoSample.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Camera2VideoSample.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Camera2VideoSample.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Camera2VideoSample.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Camera2VideoSample.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Camera2VideoSample.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Camera2VideoSample.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Camera2VideoSample.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Camera2VideoSample.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Camera2VideoSample.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Camera2VideoSample.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Camera2VideoSample.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Camera2VideoSample.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Camera2VideoSample.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Camera2VideoSample.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Camera2VideoSample.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Camera2VideoSample.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Camera2VideoSample.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Camera2VideoSample.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Camera2VideoSample.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060005
			public const int horizontal_page_margin = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int margin_huge = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int margin_large = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int margin_medium = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int margin_small = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int margin_tiny = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int vertical_page_margin = 2131099654;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_info = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tile = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int OptionHostName = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int OptionPort = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int OptionRemoteServer = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int OptionsButton = 2131165204;
			
			// aapt resource value: 0x7f07000f
			public const int ResultFullName = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int ResultMessage = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int ResultResultState = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int ResultRunSingleMethodTest = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int ResultStackTrace = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int ResultsFailed = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int ResultsId = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int ResultsIgnored = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int ResultsInconclusive = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int ResultsMessage = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int ResultsPassed = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int ResultsResult = 2131165192;
			
			// aapt resource value: 0x7f070013
			public const int RunTestsButton = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int TestSuiteListView = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int container = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int info = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int texture = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int video = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_camera2_video = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int options = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int results = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int test_result = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int test_suite = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int description_info = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int intro_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int record = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int stop = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050003
			public const int AppTheme = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int MaterialTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Base = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Theme_Sample = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int Widget = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int Widget_SampleMessage = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int Widget_SampleMessageTile = 2131034118;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
