#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ToolbarFun.Resource", IsApplication=true)]

namespace ToolbarFun
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_action_content_create = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_action_content_save = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_copy_holo_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_cut_holo_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_paste_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_menu_search_holo_dark = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int edit_toolbar = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int main_content = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int menu_copy = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int menu_cut = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int menu_edit = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int menu_paste = 2131230725;
			
			// aapt resource value: 0x7f080008
			public const int menu_preferences = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int menu_save = 2131230727;
			
			// aapt resource value: 0x7f080000
			public const int toolbar = 2131230720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int edit_menus = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int top_menus = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
